### ISSUE TITLE
savedata info apollo project

### ISSUE THREAD

**Issue by naru232** [bucanero/apollo-saves#1]
good morning,

hello bucanero i am ashura on psx place i am sending to you thru this message the link of the savedatas that i have uploaded, due to i was banned on psx place when i posted the link over there, thank you in advance i am sending to you the mega link at this moment, have a nice day

https://mega.nz/#!q5kjiTAb!FSJt13nNt6naCInYLloTnZeK3BYGmmW_1DcXE_FRcPw

**Comment by bucanero** [comment]
hello,

oh I saw your post, I think the issue was posting DLC links, the moderators enforce the rules against prohibited links.

Anyways, I got the the file with your saves, but there's no description of what game is which folder, nor a description of what stuff is in the save (e.g. "Yakuza 3, completed game, all unlocked on Hard difficulty") so I can't do much with that

Please, could you make a .Zip for each save-game folder, and then share a message or text file explaining each save-game? That way I can upload and add them to the database, I don't want to be guessing what game is it or what is the save-game for.

thanks!

**Comment by naru232** [comment]
sure bucanero jeje it will take me a while but i will do my best jeje to work on the zip files in order to leave the description on those

**Comment by naru232** [comment]
i will upload along with the zip a text that will show up the savegame code along with descripton just like this example

blus00000-the evil within-all weapons unlocked

**Comment by naru232** [comment]
hello bucanero i managed to upload the new information, this one will have included the description on the saves information and also what does have each one, i managed to create only one text file for all saves, let me know if you have any questions about them jeje, best regards here is the link

https://mega.nz/#!ul0FkaoJ!47ECtIabc9Gl0hKr0QW3MYS2oCxuMzpOrC4ZakOlDF8

**Comment by bucanero** [comment]
thanks for sharing, I've got the saves and descriptions now. Next time I've a chance I'll upload them to the database.

The process will be much easier on the next version with the `Export to Zip` function. Most of the work will be done by the app, then the user would have just to take the .zip files from the USB device and upload the zip and description. It will save time and avoid troubles.

**Comment by naru232** [comment]
youre welcome bucanero jeje everything to help any time on these projects that are excellent to be develop, especially on cex ps3 that this one will be more useful than on a dex rebug console jeje and yes that will be excellent in order to me also to be able to upload the saves that i was not able to copy from my ps3 to be uploaded

**Comment by bucanero** [comment]
Updated saves have been published to the database.

Keep an eye for the next version with the `export to zip` function. 😄
