### ISSUE TITLE
[Upload save]

### ISSUE THREAD

**Issue by Rhatz** [bucanero/apollo-saves#45]
- **Game name:** Shadow of the Tomb Raider
- **Title ID:** CUSA10872
- **Save description:** This is just a test
- **Zip file:** (attach or link the `.zip` file)
[00000001.zip](https://github.com/bucanero/apollo-saves/files/7820767/00000001.zip)

**Comment by bucanero** [comment]
hello,
if you want to add this save to the list, please add a description 👍  thanks

**Comment by junaidd007** [comment]
Game name: Horizon Zero Dawn: Complete Edition
Title ID: ANY VERSION of the game
Save description: I got this from CUSA01967 but I tested it on CUSA07320 and it worked.
[checkpoint.zip](https://github.com/bucanero/apollo-saves/files/7918304/checkpoint.zip)

**Comment by junaidd007** [comment]
this is a new save game I made using CUSA07320 but this can work on prolly any version of the game
[CUSA07320.zip](https://github.com/bucanero/apollo-saves/files/7918349/CUSA07320.zip)

**Comment by bucanero** [comment]
> this is a new save game I made using CUSA07320 but this can work on prolly any version of the game [CUSA07320.zip](https://github.com/bucanero/apollo-saves/files/7918349/CUSA07320.zip)

thanks for uploading the save. Could you provide some description for this Horizon save, like "completed game, all unlocked" ?

**Comment by junaidd007** [comment]
> > this is a new save game I made using CUSA07320 but this can work on prolly any version of the game [CUSA07320.zip](https://github.com/bucanero/apollo-saves/files/7918349/CUSA07320.zip)
> 
> thanks for uploading the save. Could you provide some description for this Horizon save, like "completed game, all unlocked"?

this is [where](https://www.thetechgame.com/Downloads/id=230781/us-horizon-zero-dawn-complete-edition-all-machines-catalogued-all-cores-overridden-save-set.html) I got it from. I mainly wanted it for the New Game+ which you can only do after completing the game. So after loading this save, you just make your loadout and then go to options to set your New Game+ loadout and start the New Game+ from the menu. You will have all the weapons, upgrades and money.

**Comment by bucanero** [comment]
> this is [where](https://www.thetechgame.com/Downloads/id=230781/us-horizon-zero-dawn-complete-edition-all-machines-catalogued-all-cores-overridden-save-set.html) I got it from. I mainly wanted it for the New Game+ which you can only do after completing the game. So after loading this save, you just make your loadout and then go to options to set your New Game+ loadout and start the New Game+ from the menu. You will have all the weapons, upgrades and money.

thanks, I've uploaded the save 👍 ( 64ce10790d9f8dc8c8a5c8e92fc8a3b9cbede7bb)

**Comment by junaidd007** [comment]
I suggest taking down this save file as it won't work at all using the conventional methods. I spent all night trying different things and the only way the save works is by doing the following:
1. Go to Apollo tool and activate your account
2. Start the game and create a manual save game which can be done only at a fireplace.
3. Now go to Apollo save tool and export save game files to your HDD. Make sure it's the manual save.
4. Open a FTP and replace the exported checkpoint.dat with the one uploaded here. It should be located in the /data/apollo/<user> folder.
5. Go back to Apollo and import the save game file in the manual save.
6. Restart your PS4 and it should work after you boot the game.

I think this game has something linked to the account since it creates a profile save file as well. I tried many things but this is the only way it worked.
